### ISSUE TITLE
'DatabaseWrapper' object has no attribute 'schema_name'

### ISSUE THREAD

**Issue by JurajKavka** [centralniak/cmsplugin_gallery#30]
When I'm saving the gallery i get this error.

```
'DatabaseWrapper' object has no attribute 'schema_name'
```

I'm using Postgres and my database settings are:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'name',
        'USER': 'user',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
```

```
  File "/home/juro/work/prog/web/dj/weblso/.env/lib/python2.7/site-packages/cmsplugin_gallery/models.py", line 27, in __call__          
    if connection.schema_name:
```

Any help? Thank you.

**Comment by vinitkumar** [comment]
@JurajKavka this is fixed now. https://pypi.org/project/cmsplugin_gallery/0.6.5/

Kindly upgrade to the latest version from pypi:

`pip install cmsplugin_gallery --upgrade`

**Comment by vinitkumar** [comment]
@JurajKavka Let me know if it works fine for you now.

**Comment by JurajKavka** [comment]
@vinitkumar It's working. Thank You

**Comment by emuswailit** [comment]
You guy! Solved my problem after hours of searching
