### ISSUE TITLE
More changes needed for python3 support

### ISSUE THREAD

**Issue by k-funk** [centralniak/cmsplugin_gallery#39]
### `forms.py`
    unicode => str

### `cms_plugins.py`
    xrange => range

**Comment by vinitkumar** [comment]
@k-funk Feel free to send a PR, I will be more than happy to merge it.

**Comment by k-funk** [comment]
I was about to, but there seems to be a version mismatch going on. When I `pip install cmsplugin_gallery` i get 1.0.1 (March14 https://pypi.python.org/pypi/cmsplugin_gallery/1.0.1), but the repo here on github only shows master as 1.0.0 (Feb20).

**Comment by vinitkumar** [comment]
@k-funk That's my bad. I had some commits on my local that was not yet merged to the upstream. Please check the latest master now. All code should be there.
